  // Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useEffect, useState } from 'react';

const aemcontentfragmentblock = () => {
  const [data, setData] = useState(null);
  useEffect(() => {
    // Replace with your actual publish endpoint and query
    const endpoint = 'https://publish-p8661-e624335.adobeaemcloud.com/content/_cq_graphql/aemuniversaleditor/endpoint.json';
    const query = `
      {
        authorList {
          items {
            authorName
            book
          }
        }
      }
    `;

    fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query }),
    })
      .then((res) => res.json())
      .then((result) => setData(result.data.authorList.items))
      .catch((error) => console.error('Error fetching content fragment data:', error));
  }, []);

  if (!data) return <div>Loading...</div>;

  return (
    <div>
      <h2>authorList from AEM Content Fragment</h2>
      <ul>
        {data.map((author, idx) => (
          <li key={idx}>
            <strong>{author.authorName}</strong>
            <p>{author.book}</p>
            <em>By: Samar Yadav</em>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default aemcontentfragmentblock;
